### PR TITLE
[simulation] Fix non-executable global gates in kernels

### LINKED ISSUE #89: [simulation] mismatch in kernel.qubits and actual gates' qubits
I am running the new DP on 29-qubit(28 local) dj circuit and will encounter this mismatch in `kernel.qubits` and the actual gates qubits. Here there's the `H` gate on `Q1` but `Q1` is not in `kernel.qubits`
```
cost = 10.4
Kernel schedule with 1 kernels: cost = 10.4
Kernel 0: fusion, qubits [0, 28], gates CircuitSeq {
  Q1 = h(Q1)
  Q28 = u2(Q28, P1, P1)
  Q0 = h(Q0)
  [Q0, Q28] = cx(Q0, Q28)
  Q0 = h(Q0)
}
```

This can be reproduced by running with the following `KernelCost`:
```
KernelCost kernel_cost(
      /*fusion_kernel_costs=*/{0, 10.4, 10.400001, 10.400002, 11, 40, 46, 66},
      /*shared_memory_init_cost=*/10,
      /*shared_memory_gate_cost=*/[](GateType type) { if (type == quartz::GateType::swap) return 1000.0; else return 0.8; },
      /*shared_memory_total_qubits=*/10, /*shared_memory_cacheline_qubits=*/3);
```

### PR DESCRIPTION
**Pull request by xumingkuan**
Fix #89 

Fixes a bug introduced in #78 causing non-executable global single-qubit gates to be placed in kernels.

### CODE REVIEW

File: src/quartz/simulator/schedule.cpp [hunk 1]
```diff
@@ -1074,14 +1074,22 @@ get_schedules(const CircuitSeq &sequence,
...
-                executable = false; // not local in this kernel
-                break;
+              if (wire->is_qubit()) {
+                if (schedule.is_local_qubit(wire->index)) {
+                  if (!current_kernel_qubits[wire->index]) {
+                    executable = false; // not local in this kernel
+                    break;
+                  }
+                } else {
+                  if (!sequence.gates[index]->gate->is_sparse()) {
```
Comment (xumingkuan) [inline src/quartz/simulator/schedule.cpp:1088]: We can put these (for example global X) gates in a separate kernel later.

Comment (caoshiyi) [reply src/quartz/simulator/schedule.cpp:1088]: Looks good!
